<script setup>
import { computed, ref } from 'vue'
import { useAppStore } from '../stores/appStore'
const store=useAppStore(); const step=ref(0); const emit=defineEmits(['done'])
const slides=[{icon:'⌂',eyebrow:'WELCOME TO YOUR SPACE',title:'See your day in one calm dashboard.',body:'Your habits, health, learning, goals, calendar, and money records come together without losing their individual detail.'},{icon:'⌁',eyebrow:'BUILD YOUR ROUTINE',title:'Start with the trackers that matter to you.',body:'Add your first habit, check-in, movement, hydration, study, goal, or money record. Everything begins empty and becomes yours.'},{icon:'✦',eyebrow:'ASK YOUR TRACKER',title:'Turn your records into a useful next step.',body:'The DLT assistant answers from your current tracker snapshot and remembers recent conversation on this device.'}]
const current=computed(()=>slides[step.value]); function finish(){const uid=store.user?.uid;if(uid)localStorage.setItem(`dlt-onboarding:${uid}`,'done');store.isNewUserOnboardingPending=false;emit('done')}
</script>
<template><div class="tour-backdrop"><section class="tour-card" role="dialog" aria-modal="true" aria-labelledby="tour-title"><button class="tour-skip" @click="finish">Skip tour</button><div class="tour-icon">{{ current.icon }}</div><small>{{ current.eyebrow }}</small><h2 id="tour-title">{{ current.title }}</h2><p>{{ current.body }}</p><div class="tour-dots"><i v-for="(_,i) in slides" :key="i" :class="{active:i===step}"></i></div><footer><button v-if="step" @click="step--">Back</button><button class="tour-next" @click="step<slides.length-1?step++:finish()">{{ step<slides.length-1?'Continue':'Open my dashboard' }} →</button></footer></section></div></template>
<style scoped>.tour-backdrop{position:fixed;inset:0;z-index:10000;display:grid;place-items:center;padding:18px;background:#12201994;backdrop-filter:blur(7px)}.tour-card{position:relative;width:min(520px,100%);box-sizing:border-box;padding:42px;border:1px solid #dbe5d8;border-radius:25px;background:#fbfcf8;color:#2c4536;box-shadow:0 30px 90px #0e181344;animation:tour-in .35s ease}.tour-skip{position:absolute;right:20px;top:18px;border:0;background:transparent;color:#76877b;cursor:pointer}.tour-icon{width:64px;height:64px;display:grid;place-items:center;margin-bottom:27px;border-radius:18px;background:#e7eee1;color:#4e7658;font-size:31px}.tour-card small{font-size:9px;letter-spacing:1.6px;color:#6f8e76}.tour-card h2{font-size:32px;line-height:1.12;font-weight:500;letter-spacing:-1px;margin:11px 0 15px}.tour-card p{color:#718078;font-size:14px;line-height:1.75}.tour-dots{display:flex;gap:6px;margin:27px 0}.tour-dots i{width:7px;height:7px;border-radius:5px;background:#ccd7cb}.tour-dots i.active{width:24px;background:#60866b}.tour-card footer{display:flex;justify-content:flex-end;gap:8px}.tour-card footer button{border:1px solid #d7e1d5;background:transparent;color:#385443;padding:11px 15px;border-radius:9px;cursor:pointer}.tour-card footer .tour-next{background:#37664d;color:white;border-color:#37664d}@keyframes tour-in{from{opacity:0;transform:translateY(15px) scale(.97)}}@media(max-width:600px){.tour-card{padding:34px 24px}.tour-card h2{font-size:27px}}</style>
