<script setup>
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAppStore } from '../stores/appStore'
const store = useAppStore()
const router = useRouter()
const profileDialog = ref(null)
const profileButton = ref(null)
const displayName = computed(() => store.username || store.user?.email?.split('@')[0] || 'Your account')
const initials = computed(() => displayName.value.slice(0, 2).toUpperCase())
const joined = computed(() => {
  const date = store.user?.metadata?.creationTime
  return date ? new Date(date).toLocaleDateString('en-US', { month: 'long', year: 'numeric' }) : 'Not available'
})
const themes = [{ id: 'light', name: 'Light', icon: '☼' }, { id: 'navy', name: 'Navy', icon: '◐' }, { id: 'dark', name: 'Dark', icon: '☾' }]
const groups = [
  { title: 'Workspace', items: [ { to: '/', label: 'Overview', path: 'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z' }, { to: '/goals', label: 'Goals', path: 'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10 M12 11v2' }, { to: '/events', label: 'Calendar', path: 'M5 5h14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2 M7 3v4 M17 3v4 M3 11h18' } ] },
  { title: 'Everyday', items: [ { to: '/habits', label: 'Daily habits', path: 'M9 6h12 M9 12h12 M9 18h12 M3 6l1 1 2-3 M3 12l1 1 2-3 M3 18l1 1 2-3' }, { to: '/check-in', label: 'Daily check-in', path: 'M12 21s-7-4.35-7-10A4 4 0 0 1 12 8a4 4 0 0 1 7 3c0 5.65-7 10-7 10z' }, { to: '/study', label: 'Study space', path: 'M4 4h16v17H6a2 2 0 0 1-2-2V4 M4 17h16 M8 8h8 M8 11h5' }, { to: '/fitness', label: 'Movement', path: 'M3 12h4l3-8 4 16 3-8h4' }, { to: '/water', label: 'Hydration', path: 'M12 3s-7 7-7 12a7 7 0 0 0 14 0c0-5-7-12-7-12z' }, { to: '/anime', label: 'Watchlist', path: 'M5 4h14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2 M10 8l6 4-6 4z' } ] },
  { title: 'Your money', items: [ { to: '/finance', label: 'Expenses', path: 'M4 5h16v14H4z M4 10h16 M7 15h4' }, { to: '/savings', label: 'Savings', path: 'M3 9l9-6 9 6H3 M5 12v7 M10 12v7 M15 12v7 M20 12v7 M3 21h18' } ] },
  { title: 'Insights & tools', items: [ { to: '/reports', label: 'Reports', path: 'M4 19V9 M10 19V5 M16 19v-7 M22 19V3 M2 21h22' }, { to: '/activity', label: 'Activity', path: 'M4 6h16 M4 12h16 M4 18h10' }, { to: '/search', label: 'Search', path: 'M11 4a7 7 0 1 0 0 14 7 7 0 0 0 0-14 M16 16l5 5' }, { to: '/notifications', label: 'Notifications', path: 'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9 M10 21h4' }, { to: '/achievements', label: 'Achievements', path: 'M8 4h8v5a4 4 0 0 1-8 0V4 M8 6H4v2a4 4 0 0 0 4 4 M16 6h4v2a4 4 0 0 1-4 4 M12 13v5 M8 21h8' }, { to: '/ai-insights', label: 'AI insights', path: 'M12 3l1.7 5.3L19 10l-5.3 1.7L12 17l-1.7-5.3L5 10l5.3-1.7L12 3 M19 16l.7 2.3L22 19l-2.3.7L19 22l-.7-2.3L16 19l2.3-.7L19 16' }, { to: '/settings', label: 'Settings', path: 'M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6 M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.5V21h-4v-.1a1.7 1.7 0 0 0-1-1.5 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9 1.7 1.7 0 0 0-1.5-1H3v-4h.1a1.7 1.7 0 0 0 1.5-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1a1.7 1.7 0 0 0 1.9.3 1.7 1.7 0 0 0 1-1.5V3h4v.1a1.7 1.7 0 0 0 1 1.5 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.5 1h.1v4h-.1a1.7 1.7 0 0 0-1.5 1' } ] },
]
function openProfile() { profileDialog.value.showModal() }
function closeProfile() { profileDialog.value.close(); profileButton.value?.focus() }

async function logout() { await store.logoutUser(); router.push('/login') }
</script>
<template>
  <div class="life-nav" :class="{ compact: store.isSidebarCollapsed }">
    <div class="life-brand"><router-link to="/" aria-label="Daily Life Tracker home"><span class="life-monogram">d.</span><span v-if="!store.isSidebarCollapsed"><strong>Daily life</strong><small>A little better, every day.</small></span></router-link><button class="life-collapse" @click="store.toggleSidebar()" :aria-label="store.isSidebarCollapsed ? 'Expand navigation' : 'Collapse navigation'" :aria-expanded="!store.isSidebarCollapsed">{{ store.isSidebarCollapsed ? '›' : '‹' }}</button></div>
    <nav class="life-links" aria-label="Main navigation"><section v-for="group in groups" :key="group.title"><h2 v-if="!store.isSidebarCollapsed">{{ group.title }}</h2><router-link v-for="item in group.items.filter(entry => entry.to !== '/ai-insights')" :key="item.to" :to="item.to" class="life-link" exact-active-class="selected" :aria-label="item.to === '/search' ? 'Ask AI' : item.label" :title="store.isSidebarCollapsed ? (item.to === '/search' ? 'Ask AI' : item.label) : undefined"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path :d="item.path" /></svg><span v-if="!store.isSidebarCollapsed">{{ item.to === '/search' ? 'Ask AI' : item.label }}</span><i v-if="!store.isSidebarCollapsed" class="life-active-dot"></i></router-link></section></nav>
    <footer class="life-footer"><div v-if="!store.isSidebarCollapsed" class="life-appearance"><span>Appearance</span><div class="life-theme-options" role="group" aria-label="Color theme"><button v-for="theme in themes" :key="theme.id" :aria-pressed="store.theme === theme.id" @click="store.setTheme(theme.id)"><i>{{ theme.icon }}</i>{{ theme.name }}</button></div></div><button v-else class="life-theme-compact" @click="openProfile" aria-label="Appearance and account settings">☼</button>
    <button ref="profileButton" class="life-profile" @click="openProfile" :aria-label="`Open profile for ${displayName}`" aria-haspopup="dialog"><span class="life-avatar">{{ initials }}</span><span v-if="!store.isSidebarCollapsed" class="life-profile-copy"><strong>{{ displayName }}</strong><small>View your account</small></span><span v-if="!store.isSidebarCollapsed" class="life-profile-arrow">↗</span></button></footer>
    <Teleport to="body"><dialog ref="profileDialog" class="life-account" aria-labelledby="account-title" @click="event => { if (event.target === profileDialog) closeProfile() }" @cancel.prevent="closeProfile"><button class="life-account-close" @click="closeProfile" aria-label="Close profile">×</button><span class="life-avatar account-avatar">{{ initials }}</span><p class="account-eyebrow">YOUR PERSONAL SPACE</p><h2 id="account-title">{{ displayName }}</h2><p class="account-subtitle">Your account, all in one place.</p><dl><div><dt>Email address</dt><dd>{{ store.user?.email || 'Not available' }}</dd></div><div><dt>Member since</dt><dd>{{ joined }}</dd></div></dl><div class="life-appearance"><span>Appearance</span><div class="life-theme-options" role="group" aria-label="Profile color theme"><button v-for="theme in themes" :key="theme.id" :aria-pressed="store.theme === theme.id" @click="store.setTheme(theme.id)"><i>{{ theme.icon }}</i>{{ theme.name }}</button></div></div><button class="life-signout" @click="logout">Sign out <span>→</span></button></dialog></Teleport>
  </div>
</template>
<style scoped>
.life-nav { --nav-bg:#fff; --nav-ink:#304c3d; --nav-muted:#87978b; --nav-line:#e7ede7; --nav-selected:#eaf1e9; height:100dvh; width:290px; padding:28px 22px 18px; box-sizing:border-box; display:flex; flex-direction:column; background:var(--nav-bg); border-right:1px solid var(--nav-line); }
[data-theme="dark"] .life-nav { --nav-bg:#1c2922; --nav-ink:#e1ebe2; --nav-muted:#a0afa4; --nav-line:#35473a; --nav-selected:#314839; }
[data-theme="navy"] .life-nav { --nav-bg:#182b37; --nav-ink:#dceaf0; --nav-muted:#9bafbb; --nav-line:#304854; --nav-selected:#294655; }
.life-brand { display:flex; align-items:center; justify-content:space-between; margin-bottom:34px; }.life-brand a { display:flex; gap:11px; align-items:center; text-decoration:none; color:var(--nav-ink); }.life-monogram { background:#3d7156; color:#fff; font-size:28px; letter-spacing:-2px; width:39px; height:39px; border-radius:12px; display:grid; place-items:center; padding-right:3px; }.life-brand strong { font-size:17px; font-weight:600; letter-spacing:-.5px; }.life-brand small { display:block; font-size:9px; color:var(--nav-muted); margin-top:3px; }.life-collapse { border:1px solid var(--nav-line); background:var(--nav-bg); border-radius:7px; color:var(--nav-muted); width:24px; height:26px; font-size:20px; cursor:pointer; }
.life-links { overflow-y:auto; min-height:0; flex:1; scrollbar-width:thin; scrollbar-color:var(--nav-line) transparent; }.life-links section { margin-bottom:23px; }.life-links h2 { margin:0 12px 8px; color:var(--nav-muted); font-size:9px; letter-spacing:1.4px; font-weight:500; text-transform:uppercase; }.life-link { display:flex; align-items:center; gap:12px; height:41px; padding:0 12px; margin-bottom:3px; border-radius:8px; color:var(--nav-ink); text-decoration:none; font-size:12px; transition:background .18s,transform .18s; }.life-link svg { width:18px; height:18px; flex-shrink:0; opacity:.8; }.life-link.selected { background:var(--nav-selected); font-weight:600; }.life-link:hover { background:var(--nav-selected); transform:translateX(2px); }.life-active-dot { display:none; width:5px; height:5px; margin-left:auto; border-radius:50%; background:#71906c; }.selected .life-active-dot { display:block; }
.life-footer { flex-shrink:0; border-top:1px solid var(--nav-line); padding-top:17px; }.life-appearance > span { display:block; font-size:10px; color:var(--nav-muted,#7e8d80); margin-bottom:10px; }.life-theme-options { display:flex; gap:4px; padding:4px; border:1px solid var(--nav-line,#e0e7e0); border-radius:10px; background:var(--nav-selected,#edf2ec); }.life-theme-options button { flex:1; padding:7px 2px; border:0; background:transparent; border-radius:7px; color:var(--nav-muted,#748578); font-size:10px; display:flex; gap:5px; align-items:center; justify-content:center; cursor:pointer; }.life-theme-options button[aria-pressed=true] { background:var(--nav-bg,#fff); color:var(--nav-ink,#3c5c47); box-shadow:0 1px 5px #21302110; }.life-theme-options i { font-style:normal; font-size:15px; }
.life-profile { width:100%; display:flex; align-items:center; gap:10px; border:0; border-radius:10px; background:transparent; padding:15px 3px 2px; text-align:left; color:var(--nav-ink); cursor:pointer; }.life-avatar { width:35px; height:35px; border-radius:11px; display:grid; place-items:center; background:#e8edde; color:#647e50; font-size:12px; font-weight:600; flex-shrink:0; }.life-profile-copy { flex:1; min-width:0; }.life-profile-copy strong { display:block; overflow:hidden; text-overflow:ellipsis; font-size:12px; font-weight:500; }.life-profile-copy small { display:block; font-size:9px; color:var(--nav-muted); margin-top:4px; }.life-profile-arrow { color:var(--nav-muted); }.life-profile:hover .life-profile-arrow { color:var(--nav-ink); }.life-theme-compact { background:var(--nav-selected); color:var(--nav-ink); border:0; border-radius:8px; width:40px; height:34px; cursor:pointer; }
.life-nav.compact { width:108px; padding:28px 25px 18px; }.compact .life-brand { position:relative; }.compact .life-collapse { position:absolute; right:-34px; top:7px; }.compact .life-links section { margin-bottom:13px; padding-bottom:10px; border-bottom:1px solid var(--nav-line); }.compact .life-link { justify-content:center; padding:0; }.compact .life-profile { justify-content:center; }
.life-account { margin:auto; max-height:calc(100dvh - 40px); overflow-y:auto; border:1px solid var(--border-color); background:var(--bg-primary,#fff); color:var(--text-primary); border-radius:22px; width:min(400px,calc(100vw - 36px)); padding:32px; box-shadow:0 25px 90px #13201933; }.life-account::backdrop { background:#15241d66; backdrop-filter:blur(4px); }.life-account-close { position:absolute; top:12px; right:15px; background:transparent; color:var(--text-muted); border:0; font-size:24px; cursor:pointer; }.account-avatar { width:55px; height:55px; font-size:18px; margin-bottom:24px; }.account-eyebrow { font-size:9px; letter-spacing:1.5px; color:var(--text-muted); }.life-account h2 { margin:10px 0 5px; font-size:26px; font-weight:500; overflow-wrap:anywhere; }.account-subtitle { font-size:12px; color:var(--text-muted); }.life-account dl { margin:25px 0; }.life-account dl div { padding:14px 0; border-bottom:1px solid var(--border-color); }.life-account dt { font-size:10px; color:var(--text-muted); margin-bottom:6px; }.life-account dd { margin:0; font-size:13px; overflow-wrap:anywhere; }.life-signout { display:flex; justify-content:space-between; width:100%; margin-top:25px; border:1px solid var(--border-color); border-radius:9px; padding:11px 13px; background:transparent; color:var(--text-primary); font-size:12px; cursor:pointer; }
@media(max-width:768px) { .life-nav { padding-top:70px; } }
[data-theme="dark"] .life-account { --nav-bg:#1c2922; --nav-ink:#e1ebe2; --nav-muted:#a0afa4; --nav-line:#35473a; --nav-selected:#314839; }
[data-theme="navy"] .life-account { --nav-bg:#182b37; --nav-ink:#dceaf0; --nav-muted:#9bafbb; --nav-line:#304854; --nav-selected:#294655; }
</style>
